### PR TITLE
Now work for qbcore

### PR DESCRIPTION
**Pull request by Wick89**
Now work for qbcore

### CODE REVIEW

**Comment by gimicze** [comment]
Thank you! 💯

I'll review the code thoroughly next week and probably propose some changes to optimise and clarify logic flow. (Also to unify the code style)

I've had a quick look for now and it seems like there won't be much work to do though.

I'm sure the users will appreciate this!

Will get back to you later.

**Comment by ItsVinnyX** [comment]
Update on this? Does not work too well.

**Comment by LightUpFam** [comment]
?? need this

**Comment by KamuiKody** [comment]
not sure if this has been confirmed yet but i am going to be picking this project up regaurdless. I forked it. Found a large memory leak im going to optimize it and convert it to work with qb and do a new PR

**Comment by Wick89** [comment]
have rework on it and now work for it new updated QB

**Comment by Roermond-Roleplay** [comment]
pls update this i need it so bad

**Pull request closed without merging**
