### PR TITLE
sync never disables

### PR DESCRIPTION
**Pull request by KamuiKody**
ends up in an endless repeating loop

### CODE REVIEW

**Review by gimicze — COMMENTED** [review]
I understand that these checks may cause problems for you, however in my tests it wasn't possible to create an endless loop. Disabling these lines would cause serious desynchronisation problems across clients. Do you have logs from when this ends up as endless loop?

**Comment by KamuiKody** [comment]
I saw no syncing issues on testing u do realize that adding a loop there does not prevent that event from moving on basically u could do the same thing with a check much more efficiently than a loop. Whats the need for a log it would hit over 70mw when as a fired continued over a few seconds then crash ur game i removed the useless sync and now it runs at 0.07 without optimizing anything else at all. If taking it out doesnt work u need to find a better way to sync cuz that aint it.

**Comment by gimicze** [comment]
Then do it more efficiently, if you see another way 🙂 by the way, if this ever resulted as an endless loop, it would mean the client got stuck and couldn't synchronise with server, which I suppose it doesn't, correct?

**Comment by KamuiKody** [comment]
You dk realize you loops do nothing but run right? They dont make anything wait except for that first 10ms… a loop like that isnt going to sync the server. Im also not going to sit here and argue about it… if you dont want to fix the issue i resolved people are going to see ur resource as unusable

**Comment by gimicze** [comment]
Sorry you feel that way. There have been no reports of this causing any issues for a year and approx. 5000 downloads until now and I wasn't able to reproduce the behaviour you're describing, hence there's no reason to make any changes to parts of the code which you obviously don't understand. (And by the way, the script sits at 0.01 to 0.05 under load for me)

**Pull request closed without merging**
